# Generated by Django 5.0 on 2024-01-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fonction',
            field=models.CharField(blank='True', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profi_h.png', upload_to='profile/'),
        ),
    ]
