# Generated by Django 5.0 on 2024-01-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_userprofile_fonction_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fonction',
            new_name='profession',
        ),
    ]
