# Generated by Django 5.0 on 2024-01-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_rename_fonction_userprofile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='commune',
            field=models.CharField(blank='True', max_length=50, null=True),
        ),
    ]
