# Generated by Django 5.0 on 2024-01-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='1', upload_to='profile/'),
            preserve_default=False,
        ),
    ]
