# Generated by Django 4.2.6 on 2023-12-01 17:26

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoVehi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=22, max_length=30, prefix='catveh', unique=True)),
                ('category', models.CharField(max_length=10)),
                ('image', models.ImageField(default='catego_prod.jpg', upload_to='category_vehi')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categorys Vehicules',
            },
        ),
        migrations.CreateModel(
            name='ChargeAdminis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('montant', models.IntegerField(default=0.0)),
                ('cpte_comptable', models.CharField(max_length=100)),
                ('Num_piece', models.CharField(max_length=100)),
                ('Num_fact', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=30, null=True)),
                ('cout', models.IntegerField()),
                ('date_achat', models.DateField()),
                ('date_saisie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Typecontravention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=15, unique=True)),
                ('marque', models.CharField(max_length=20)),
                ('kilometrage', models.IntegerField()),
                ('image', models.ImageField(upload_to='vehicule')),
                ('photo_carte_grise', models.ImageField(upload_to='Photo_Carte_Grise')),
                ('num_cart_grise', models.CharField(max_length=100, unique=True)),
                ('num_Chassis', models.CharField(max_length=100, unique=True)),
                ('date_acquisition', models.DateField()),
                ('cout_acquisition', models.IntegerField(default=0)),
                ('dat_edit_carte_grise', models.DateField()),
                ('date_mis_service', models.DateField()),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catego_vehicule', to='PB_Entreprise.categovehi')),
            ],
        ),
        migrations.CreateModel(
            name='VisiteTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField()),
                ('date_prochaine_visite', models.DateField()),
                ('cout', models.IntegerField(default=0.0)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='PB_Entreprise.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Reparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField()),
                ('date_sortie', models.DateTimeField()),
                ('num_fich_repat', models.IntegerField()),
                ('identification', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('cout', models.IntegerField(default=0.0)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='PB_Entreprise.piece')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparations', to='PB_Entreprise.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chauffeur', models.CharField(max_length=50)),
                ('cpte_comptable', models.CharField(max_length=100)),
                ('numero_fact', models.CharField(max_length=20)),
                ('Num_piece', models.CharField(max_length=100)),
                ('montant', models.IntegerField(default=0.0)),
                ('date', models.DateField()),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to='PB_Entreprise.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Entretien', models.DateField()),
                ('date_proch_Entretien', models.DateField()),
                ('cout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='PB_Entreprise.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Contravention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0.0)),
                ('type_contravention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PB_Entreprise.typecontravention')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PB_Entreprise.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('montant', models.IntegerField(default=0.0)),
                ('cpte_comptable', models.CharField(max_length=100)),
                ('Num_piece', models.CharField(max_length=100)),
                ('Num_fact', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargevariables', to='PB_Entreprise.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeFixe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('montant', models.IntegerField(default=0.0)),
                ('cpte_comptable', models.CharField(max_length=100)),
                ('Num_piece', models.CharField(max_length=100)),
                ('Num_fact', models.CharField(max_length=100)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargefixes', to='PB_Entreprise.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_proch_assur', models.DateField()),
                ('cout', models.IntegerField(default=0.0)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assurances', to='PB_Entreprise.vehicule')),
            ],
        ),
    ]
