# Generated by Django 4.2.6 on 2023-12-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0002_alter_recette_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparation',
            name='piece',
        ),
        migrations.AddField(
            model_name='piece',
            name='reparation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='PB_Entreprise.reparation'),
            preserve_default=False,
        ),
    ]
