# Generated by Django 4.2.6 on 2023-12-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0003_remove_reparation_piece_piece_reparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparation',
            name='date_saisie',
            field=models.DateField(auto_now_add=True),
        ),
    ]
