# Generated by Django 4.2.6 on 2023-12-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0004_alter_reparation_date_saisie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categovehi',
            name='category',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
