# Generated by Django 5.0 on 2023-12-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0005_alter_categovehi_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargefixe',
            name='libelle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chargevariable',
            name='libelle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='cout',
            field=models.IntegerField(default=0),
        ),
    ]
