# Generated by Django 5.0 on 2023-12-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0006_alter_chargefixe_libelle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='date_achat',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='piece',
            name='date_saisie',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='montant',
            field=models.IntegerField(default=0),
        ),
    ]
