# Generated by Django 5.0 on 2024-01-02 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0007_alter_piece_date_achat_alter_piece_date_saisie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempsArret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recet', models.IntegerField(default=0)),
                ('motif', models.CharField(choices=[('Reparation', 'Réparation'), ('Visite', 'Visite'), ('Accident', 'Accident'), ('Entretien', 'Entretien'), ('Autre', 'Autre')], max_length=20)),
                ('motif_autre', models.CharField(blank=True, max_length=255, null=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temps_arrets', to='PB_Entreprise.vehicule')),
            ],
        ),
    ]
