# Generated by Django 5.0 on 2024-01-02 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0008_tempsarret'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsarret',
            name='date_saisie',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 2, 23, 46, 18, 182156, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
