# Generated by Django 5.0 on 2024-01-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0011_decaissement_encaissement_cart_stationnement_patente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Decaissement',
        ),
        migrations.DeleteModel(
            name='Encaissement',
        ),
    ]
