# Generated by Django 5.0 on 2024-01-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0012_delete_decaissement_delete_encaissement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decaissement_Journalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_piece', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('montant', models.IntegerField(default=0)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encaissement_Journalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_piece', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=50)),
                ('montant', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
