# Generated by Django 5.0 on 2024-01-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0014_billetage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_stationnement',
            name='date_saisie',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='decaissement_journalier',
            name='date_saisie',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='encaissement_journalier',
            name='date_saisie',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patente',
            name='date_saisie',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='relicat',
            name='date_saisie',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='date_saisie',
            field=models.DateField(auto_now_add=True),
        ),
    ]
