# Generated by Django 5.0 on 2024-01-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0015_alter_cart_stationnement_date_saisie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldeJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.IntegerField(default=0)),
                ('date_saisie', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
