# Generated by Django 5.0 on 2024-01-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0016_soldejour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldejour',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
