# Generated by Django 5.0 on 2024-01-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0017_alter_soldejour_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decaissement_journalier',
            name='libelle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='encaissement_journalier',
            name='libelle',
            field=models.CharField(max_length=100),
        ),
    ]
