# Generated by Django 5.0 on 2024-01-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0018_alter_decaissement_journalier_libelle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='kilometrage',
            new_name='duree',
        ),
    ]
