# Generated by Django 5.0 on 2024-02-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0021_alter_entretien_cout'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='piece_jointe',
            field=models.ImageField(blank=True, upload_to='assurances_fil'),
        ),
        migrations.AddField(
            model_name='cart_stationnement',
            name='piece_jointe',
            field=models.ImageField(blank=True, upload_to='carte_station_fil'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='piece_jointe',
            field=models.ImageField(blank=True, upload_to='entretiens_fil'),
        ),
        migrations.AddField(
            model_name='patente',
            name='piece_jointe',
            field=models.ImageField(blank=True, upload_to='patentes_fil'),
        ),
        migrations.AddField(
            model_name='reparation',
            name='piece_jointe',
            field=models.ImageField(blank=True, upload_to='reparation_fil'),
        ),
        migrations.AddField(
            model_name='vignette',
            name='piece_jointe',
            field=models.ImageField(blank=True, upload_to='vignettes_fil'),
        ),
        migrations.AddField(
            model_name='visitetechnique',
            name='piece_jointe',
            field=models.ImageField(blank=True, upload_to='visites_fil'),
        ),
    ]
