# Generated by Django 5.0 on 2024-02-18 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0003_remove_photo_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_saisie',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 2, 18, 23, 4, 4, 798259, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateField(),
        ),
    ]
