# Generated by Django 5.0 on 2024-02-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0004_video_date_saisie_alter_video_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='date',
            new_name='date_event',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='date',
            new_name='date_phot',
        ),
    ]
