# Generated by Django 5.0.2 on 2024-02-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0008_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='name',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='nom',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
