# Generated by Django 5.0.2 on 2024-02-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0009_remove_commentaire_name_commentaire_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='nom',
            new_name='namuser',
        ),
    ]
